/**
 * 国际门户遗留 API stub（原 src/api/bussiness 已删除）
 * 仅保证旧组件可编译；调用将拒绝，请迁移至 src/api/intl 真实接口。
 */
const notImpl = (name) => (...args) => {
  console.warn(`[jgt-intl-portal] legacy API stub called: ${name}`)
  return Promise.reject(new Error(`[jgt-intl-portal] legacy API removed: ${name}`))
}

export const addAuthIp = notImpl('fofund-fap/addAuthIp')
export const asyncBatchRole = notImpl('fofund-fap/asyncBatchRole')
export const asyncQueryBatchResult = notImpl('fofund-fap/asyncQueryBatchResult')
export const cacheRefresh = notImpl('fofund-fap/cacheRefresh')
export const checkPassword = notImpl('fofund-fap/checkPassword')
export const checkWhiteOperator = notImpl('fofund-fap/checkWhiteOperator')
export const commonIpWhite = notImpl('fofund-fap/commonIpWhite')
export const commonSelectOptions = notImpl('fofund-fap/commonSelectOptions')
export const deferredLogin = notImpl('fofund-fap/deferredLogin')
export const fapFileDownload = notImpl('fofund-fap/fapFileDownload')
export const fapFileUpload = notImpl('fofund-fap/fapFileUpload')
export const forgotPassword = notImpl('fofund-fap/forgotPassword')
export const getOrgTypeByToken = notImpl('fofund-fap/getOrgTypeByToken')
export const jyAccountAll = notImpl('fofund-fap/jyAccountAll')
export const jyAccountDetail = notImpl('fofund-fap/jyAccountDetail')
export const jyAccountExport = notImpl('fofund-fap/jyAccountExport')
export const log = notImpl('fofund-fap/log')
export const logExport = notImpl('fofund-fap/logExport')
export const operatorLimitAndProType = notImpl('fofund-fap/operatorLimitAndProType')
export const passwordReset = notImpl('fofund-fap/passwordReset')
export const permissionBindOperatorEstablish = notImpl('fofund-fap/permissionBindOperatorEstablish')
export const position = notImpl('fofund-fap/position')
export const positionExport = notImpl('fofund-fap/positionExport')
export const roleCreate = notImpl('fofund-fap/roleCreate')
export const roleDelete = notImpl('fofund-fap/roleDelete')
export const roleExport = notImpl('fofund-fap/roleExport')
export const roleOperator = notImpl('fofund-fap/roleOperator')
export const rolePage = notImpl('fofund-fap/rolePage')
export const roleResource = notImpl('fofund-fap/roleResource')
export const roleSelectCode = notImpl('fofund-fap/roleSelectCode')
export const roleUpdate = notImpl('fofund-fap/roleUpdate')
export const setCommonlyUsed = notImpl('fofund-fap/setCommonlyUsed')
export const toggleLoginCommonCustomerList = notImpl('fofund-fap/toggleLoginCommonCustomerList')
export const toggleLoginCustomer = notImpl('fofund-fap/toggleLoginCustomer')
export const toggleLoginCustomerEstablishList = notImpl('fofund-fap/toggleLoginCustomerEstablishList')
export const toggleLoginCustomerList = notImpl('fofund-fap/toggleLoginCustomerList')
export const toggleLoginEstablish = notImpl('fofund-fap/toggleLoginEstablish')
export const toggleLoginType = notImpl('fofund-fap/toggleLoginType')
export const tradeHistory = notImpl('fofund-fap/tradeHistory')
export const tradeHistoryExport = notImpl('fofund-fap/tradeHistoryExport')
export const tradeHistoryPrintPDF = notImpl('fofund-fap/tradeHistoryPrintPDF')
export const userCheck = notImpl('fofund-fap/userCheck')
export const userInfoBatchChangeRoles = notImpl('fofund-fap/userInfoBatchChangeRoles')
export const userInfoBatchImport = notImpl('fofund-fap/userInfoBatchImport')
export const userInfoBatchTryConfirm = notImpl('fofund-fap/userInfoBatchTryConfirm')
export const userInfoCheckExistOtherOrg = notImpl('fofund-fap/userInfoCheckExistOtherOrg')
export const userInfoCreate = notImpl('fofund-fap/userInfoCreate')
export const userInfoExport = notImpl('fofund-fap/userInfoExport')
export const userInfoGetRoles = notImpl('fofund-fap/userInfoGetRoles')
export const userInfoGetRolesAll = notImpl('fofund-fap/userInfoGetRolesAll')
export const userInfoOperatorDelete = notImpl('fofund-fap/userInfoOperatorDelete')
export const userInfoQueryPage = notImpl('fofund-fap/userInfoQueryPage')
export const userInfoUnbind = notImpl('fofund-fap/userInfoUnbind')
export const userInfoUpdate = notImpl('fofund-fap/userInfoUpdate')
export const userLogin = notImpl('fofund-fap/userLogin')
export const userLoginOrg = notImpl('fofund-fap/userLoginOrg')
export const userLoginOrgList = notImpl('fofund-fap/userLoginOrgList')
export const userLogout = notImpl('fofund-fap/userLogout')
export const userRightsAllTradeRights = notImpl('fofund-fap/userRightsAllTradeRights')
export const userRightsBatchEditTradeRights = notImpl('fofund-fap/userRightsBatchEditTradeRights')
export const userRightsByOperatorId = notImpl('fofund-fap/userRightsByOperatorId')
export const userRightsChangeStatus = notImpl('fofund-fap/userRightsChangeStatus')
export const userRightsExport = notImpl('fofund-fap/userRightsExport')
export const userRightsGetAllJYAccounts = notImpl('fofund-fap/userRightsGetAllJYAccounts')
export const userRightsGetJyAccountsByOperatorCode = notImpl('fofund-fap/userRightsGetJyAccountsByOperatorCode')
export const userRightsSave = notImpl('fofund-fap/userRightsSave')
export const userTokenInfo = notImpl('fofund-fap/userTokenInfo')
export const userTrialLogin = notImpl('fofund-fap/userTrialLogin')
