module.exports = [
  // { name: 'vue', library: 'Vue', js: './lib/3rd/vue.min.js', css: '' },
  // { name: 'vue-router', library: 'VueRouter', js: './lib/3rd/vue-router.min.js', css: '' },
  // { name: 'vuex', library: 'Vuex', js: './lib/3rd/vuex.min.js', css: '' },
  // { name: 'echarts', library: 'echarts', js: './lib/3rd/echarts.min.js', css: '' },
  // { name: 'axios', library: 'axios', js: './lib/3rd/axios.min.js', css: '' },
  // { name: 'better-scroll', library: 'BScroll', js: './lib/3rd/bscroll.min.js', css: '' },
  // { name: 'element-ui', library: 'ELEMENT', js: './lib/3rd/element-ui-2.15.6/package/lib/index.js', css: './lib/3rd/element-ui-2.15.6/package/lib/index.css' }
  // { name: 'mockjs', library: 'Mock', js: './lib/3rd/mock.min.js', css: '' },
  // { name: 'lodash', library: '_', js: './lib/3rd/lodash.min.js', css: '' },
  // { name: 'ua-parser-js', library: 'UAParser', js: './lib/3rd/ua-parser.min.js', css: '' },
  // { name: 'js-cookie', library: 'Cookies', js: './lib/3rd/js.cookie.min.js', css: '' },
  // { name: 'nprogress', library: 'NProgress', js: './lib/3rd/nprogress.min.js', css: './lib/3rd/nprogress.css' },
  // { name: 'dayjs', library: 'dayjs', js: './lib/3rd/dayjs.min.js', css: '' },
  // { name: 'fuse.js', library: 'Fuse', js: './lib/3rd/fuse.min.js', css: '' },
  // { name: 'hotkeys-js', library: 'hotkeys', js: './lib/3rd/hotkeys.js', css: '' },
  // { name: 'qs', library: 'Qs', js: './lib/3rd/qs.js', css: '' },
  // { name: 'lowdb', library: 'low', js: './lib/3rd/low.min.js', css: '' },
  // { name: 'lowdb/adapters/LocalStorage', library: 'LocalStorage', js: './lib/3rd/LocalStorage.min.js', css: '' },
  // { name: 'screenfull', library: 'screenfull', js: './lib/3rd/screenfull.min.js', css: '' },
  // { name: 'sortablejs', library: 'Sortable', js: './lib/3rd/Sortable.min.js', css: '' },
  // { name: 'highlight.js', library: 'hljs', js: './lib/3rd/highlight.min.js', css: '' },
  // { name: 'vue-lazyload', library: 'VueLazyload', js: './lib/3rd/vue-lazyload.js', css: '' },
  // { name: 'jsencrypt', library: 'JSEncrypt', js: './lib/3rd/jsencrypt.min.js', css: '' },
]
