#----- Default SonarQube server
sonar.host.url=http://10.105.100.65:9000
# 项目名
sonar.projectKey=account-portal
# 扫描的区域，全扫
sonar.sources=./src
# newcode 基于master
sonar.newCode.referenceBranch=master
#sonartoken
sonar.login=5dfef6fed31664ce295595a847d6749014bfa5f0
#----- Default source code encoding
sonar.sourceEncoding=UTF-8
sonar.newCode.referenceBranch=master
