/**
 * 国际门户遗留 API stub（原 src/api/bussiness 已删除）
 * 仅保证旧组件可编译；调用将拒绝，请迁移至 src/api/intl 真实接口。
 */
const notImpl = (name) => (...args) => {
  console.warn(`[jgt-intl-portal] legacy API stub called: ${name}`)
  return Promise.reject(new Error(`[jgt-intl-portal] legacy API removed: ${name}`))
}

export const benchGrList = notImpl('bus-jgt-prd/benchGrList')
export const benchgrList = notImpl('bus-jgt-prd/benchgrList')
export const bmisProductPage = notImpl('bus-jgt-prd/bmisProductPage')
export const bonusPage = notImpl('bus-jgt-prd/bonusPage')
export const commonQueryByFundType = notImpl('bus-jgt-prd/commonQueryByFundType')
export const compSearch = notImpl('bus-jgt-prd/compSearch')
export const exportBmisDetailPerformance = notImpl('bus-jgt-prd/exportBmisDetailPerformance')
export const fetchCompanyDetail = notImpl('bus-jgt-prd/fetchCompanyDetail')
export const fetchCompanyList = notImpl('bus-jgt-prd/fetchCompanyList')
export const fetchDictList = notImpl('bus-jgt-prd/fetchDictList')
export const fetchPrivateFundProductList = notImpl('bus-jgt-prd/fetchPrivateFundProductList')
export const fundRateTransferDiscount = notImpl('bus-jgt-prd/fundRateTransferDiscount')
export const getBmisCompList = notImpl('bus-jgt-prd/getBmisCompList')
export const getBmisHotList = notImpl('bus-jgt-prd/getBmisHotList')
export const getBmisProductDetail = notImpl('bus-jgt-prd/getBmisProductDetail')
export const getBmisProductInfo = notImpl('bus-jgt-prd/getBmisProductInfo')
export const getBmisProductPage = notImpl('bus-jgt-prd/getBmisProductPage')
export const getBmisProductTrendInfo = notImpl('bus-jgt-prd/getBmisProductTrendInfo')
export const getComplianceConfig = notImpl('bus-jgt-prd/getComplianceConfig')
export const getFundManagerList = notImpl('bus-jgt-prd/getFundManagerList')
export const getFundPerformanceFeeDesc = notImpl('bus-jgt-prd/getFundPerformanceFeeDesc')
export const getIndexList = notImpl('bus-jgt-prd/getIndexList')
export const getProductCodeTranslate = notImpl('bus-jgt-prd/getProductCodeTranslate')
export const marketPage = notImpl('bus-jgt-prd/marketPage')
export const marketScaleList = notImpl('bus-jgt-prd/marketScaleList')
export const noticeInfo = notImpl('bus-jgt-prd/noticeInfo')
export const noticeList = notImpl('bus-jgt-prd/noticeList')
export const productInfo = notImpl('bus-jgt-prd/productInfo')
export const productInfo2 = notImpl('bus-jgt-prd/productInfo2')
export const productLabel = notImpl('bus-jgt-prd/productLabel')
export const productSearch = notImpl('bus-jgt-prd/productSearch')
export const pubDetail = notImpl('bus-jgt-prd/pubDetail')
export const pubPage = notImpl('bus-jgt-prd/pubPage')
export const queryByFundType = notImpl('bus-jgt-prd/queryByFundType')
export const queryFundType = notImpl('bus-jgt-prd/queryFundType')
export const queryTypeByComp = notImpl('bus-jgt-prd/queryTypeByComp')
export const ratePage = notImpl('bus-jgt-prd/ratePage')
export const recommandList = notImpl('bus-jgt-prd/recommandList')
export const scaleList = notImpl('bus-jgt-prd/scaleList')
export const searchAddHis = notImpl('bus-jgt-prd/searchAddHis')
export const searchBmisProduct = notImpl('bus-jgt-prd/searchBmisProduct')
export const searchGetHisRcmd = notImpl('bus-jgt-prd/searchGetHisRcmd')
export const searchProduct = notImpl('bus-jgt-prd/searchProduct')
export const shareholderList = notImpl('bus-jgt-prd/shareholderList')
export const splitBuyLimit = notImpl('bus-jgt-prd/splitBuyLimit')
