/**
 * 国际门户遗留 API stub（原 src/api/bussiness 已删除）
 * 仅保证旧组件可编译；调用将拒绝，请迁移至 src/api/intl 真实接口。
 */
const notImpl = (name) => (...args) => {
  console.warn(`[jgt-intl-portal] legacy API stub called: ${name}`)
  return Promise.reject(new Error(`[jgt-intl-portal] legacy API removed: ${name}`))
}

export const accountAsyncFileUpload = notImpl('fofund-account/accountAsyncFileUpload')
export const accountBatchDelete = notImpl('fofund-account/accountBatchDelete')
export const accountBatchDetail = notImpl('fofund-account/accountBatchDetail')
export const accountBatchDetailDelete = notImpl('fofund-account/accountBatchDetailDelete')
export const accountBatchList = notImpl('fofund-account/accountBatchList')
export const accountBatchPreview = notImpl('fofund-account/accountBatchPreview')
export const accountBatchProtocol = notImpl('fofund-account/accountBatchProtocol')
export const accountBatchSubmit = notImpl('fofund-account/accountBatchSubmit')
export const accountChangeStatus = notImpl('fofund-account/accountChangeStatus')
export const accountCopyApply = notImpl('fofund-account/accountCopyApply')
export const accountDeleteApply = notImpl('fofund-account/accountDeleteApply')
export const accountDetail = notImpl('fofund-account/accountDetail')
export const accountFile = notImpl('fofund-account/accountFile')
export const accountFileDelete = notImpl('fofund-account/accountFileDelete')
export const accountList = notImpl('fofund-account/accountList')
export const accountListRisk = notImpl('fofund-account/accountListRisk')
export const accountSaveRandomNo = notImpl('fofund-account/accountSaveRandomNo')
export const accountSaveRisk = notImpl('fofund-account/accountSaveRisk')
export const accountUpdateApply = notImpl('fofund-account/accountUpdateApply')
export const accountValidateRandomNo = notImpl('fofund-account/accountValidateRandomNo')
export const asyncFillRegister = notImpl('fofund-account/asyncFillRegister')
export const authDelete = notImpl('fofund-account/authDelete')
export const commonDictionary = notImpl('fofund-account/commonDictionary')
export const deleteBeneficiary = notImpl('fofund-account/deleteBeneficiary')
export const deleteOperator = notImpl('fofund-account/deleteOperator')
export const deleteUpload = notImpl('fofund-account/deleteUpload')
export const fileDelete = notImpl('fofund-account/fileDelete')
export const holdingDelete = notImpl('fofund-account/holdingDelete')
export const hsDictionary = notImpl('fofund-account/hsDictionary')
export const listBeneficiaryHis = notImpl('fofund-account/listBeneficiaryHis')
export const listOperatorHis = notImpl('fofund-account/listOperatorHis')
export const managerDelete = notImpl('fofund-account/managerDelete')
export const multiExcelOpenAccount = notImpl('fofund-account/multiExcelOpenAccount')
export const orgSignProtocol = notImpl('fofund-account/orgSignProtocol')
export const provinceCity = notImpl('fofund-account/provinceCity')
export const queryQxb = notImpl('fofund-account/queryQxb')
export const queryRegisterInfoByOrgCode = notImpl('fofund-account/queryRegisterInfoByOrgCode')
export const realTimeProtocol = notImpl('fofund-account/realTimeProtocol')
export const registerAllInfo = notImpl('fofund-account/registerAllInfo')
export const registerAuth = notImpl('fofund-account/registerAuth')
export const registerChangeStatus = notImpl('fofund-account/registerChangeStatus')
export const registerFile = notImpl('fofund-account/registerFile')
export const registerHolding = notImpl('fofund-account/registerHolding')
export const registerInfo = notImpl('fofund-account/registerInfo')
export const registerInst = notImpl('fofund-account/registerInst')
export const registerManager = notImpl('fofund-account/registerManager')
export const registerOpt = notImpl('fofund-account/registerOpt')
export const registerSaveAll = notImpl('fofund-account/registerSaveAll')
export const registerSaveExtend = notImpl('fofund-account/registerSaveExtend')
export const registerSaveRandomNo = notImpl('fofund-account/registerSaveRandomNo')
export const registerValidateRandomNo = notImpl('fofund-account/registerValidateRandomNo')
export const saveApply = notImpl('fofund-account/saveApply')
export const saveApplyAll = notImpl('fofund-account/saveApplyAll')
export const saveBank = notImpl('fofund-account/saveBank')
export const saveBeneficiary = notImpl('fofund-account/saveBeneficiary')
export const saveOperator = notImpl('fofund-account/saveOperator')
export const saveProduct = notImpl('fofund-account/saveProduct')
export const validateAccountRepeat = notImpl('fofund-account/validateAccountRepeat')
export const validateExistAccount = notImpl('fofund-account/validateExistAccount')
