/**
 * 国际门户遗留 API stub（原 src/api/bussiness 已删除）
 * 仅保证旧组件可编译；调用将拒绝，请迁移至 src/api/intl 真实接口。
 */
const notImpl = (name) => (...args) => {
  console.warn(`[jgt-intl-portal] legacy API stub called: ${name}`)
  return Promise.reject(new Error(`[jgt-intl-portal] legacy API removed: ${name}`))
}

export const addCredit = notImpl('gateway-http/addCredit')
export const addCreditRecord = notImpl('gateway-http/addCreditRecord')
export const addOptional = notImpl('gateway-http/addOptional')
export const allbaselist = notImpl('gateway-http/allbaselist')
export const billCanPrint = notImpl('gateway-http/billCanPrint')
export const billCreate = notImpl('gateway-http/billCreate')
export const billList = notImpl('gateway-http/billList')
export const commonSaveLog = notImpl('gateway-http/commonSaveLog')
export const creditAllProduct = notImpl('gateway-http/creditAllProduct')
export const creditedfundlist = notImpl('gateway-http/creditedfundlist')
export const creditlist = notImpl('gateway-http/creditlist')
export const deleteOptional = notImpl('gateway-http/deleteOptional')
export const feedback = notImpl('gateway-http/feedback')
export const fundBenchYieldList = notImpl('gateway-http/fundBenchYieldList')
export const fundBfMktListMerger = notImpl('gateway-http/fundBfMktListMerger')
export const fundMultiFactor = notImpl('gateway-http/fundMultiFactor')
export const fundScoreGet = notImpl('gateway-http/fundScoreGet')
export const fundShareStat = notImpl('gateway-http/fundShareStat')
export const fundcbdIncome = notImpl('gateway-http/fundcbdIncome')
export const getAccoInfo = notImpl('gateway-http/getAccoInfo')
export const getBmisFmInfo = notImpl('gateway-http/getBmisFmInfo')
export const getBondfundList = notImpl('gateway-http/getBondfundList')
export const getCompanyFundsStyleList = notImpl('gateway-http/getCompanyFundsStyleList')
export const getCompanyInfo = notImpl('gateway-http/getCompanyInfo')
export const getCompanyNameListByFundStyle = notImpl('gateway-http/getCompanyNameListByFundStyle')
export const getCompanyScalelist = notImpl('gateway-http/getCompanyScalelist')
export const getCompanyShareholderlist = notImpl('gateway-http/getCompanyShareholderlist')
export const getCompanyfundsStylelist = notImpl('gateway-http/getCompanyfundsStylelist')
export const getCreditInfo = notImpl('gateway-http/getCreditInfo')
export const getCurFundList = notImpl('gateway-http/getCurFundList')
export const getCustodianlist = notImpl('gateway-http/getCustodianlist')
export const getEquityfundList = notImpl('gateway-http/getEquityfundList')
export const getFundAvg = notImpl('gateway-http/getFundAvg')
export const getFundCreditInfo = notImpl('gateway-http/getFundCreditInfo')
export const getFundDetailMerger = notImpl('gateway-http/getFundDetailMerger')
export const getFundInfo = notImpl('gateway-http/getFundInfo')
export const getFundInfoList = notImpl('gateway-http/getFundInfoList')
export const getFundList = notImpl('gateway-http/getFundList')
export const getFundListBonus = notImpl('gateway-http/getFundListBonus')
export const getFundListMarket = notImpl('gateway-http/getFundListMarket')
export const getFundNotice = notImpl('gateway-http/getFundNotice')
export const getFundScale = notImpl('gateway-http/getFundScale')
export const getIRToken = notImpl('gateway-http/getIRToken')
export const getIndustryList = notImpl('gateway-http/getIndustryList')
export const getLiqBankAccount = notImpl('gateway-http/getLiqBankAccount')
export const getManagerlist = notImpl('gateway-http/getManagerlist')
export const getNoticeSettings = notImpl('gateway-http/getNoticeSettings')
export const getProductList = notImpl('gateway-http/getProductList')
export const getQDIIFundList = notImpl('gateway-http/getQDIIFundList')
export const getQszgInfoSpecialList = notImpl('gateway-http/getQszgInfoSpecialList')
export const getQualification = notImpl('gateway-http/getQualification')
export const getSignNoticeList = notImpl('gateway-http/getSignNoticeList')
export const invPortfolioInfo = notImpl('gateway-http/invPortfolioInfo')
export const multiTradeNoticeList = notImpl('gateway-http/multiTradeNoticeList')
export const qszgAssetportfolio = notImpl('gateway-http/qszgAssetportfolio')
export const qszgStockholdList = notImpl('gateway-http/qszgStockholdList')
export const quantificationIndustrylist = notImpl('gateway-http/quantificationIndustrylist')
export const queryAssetManagerList = notImpl('gateway-http/queryAssetManagerList')
export const queryAssetProductList = notImpl('gateway-http/queryAssetProductList')
export const queryBillSubscribe = notImpl('gateway-http/queryBillSubscribe')
export const queryBmisNoticeList = notImpl('gateway-http/queryBmisNoticeList')
export const queryCompanyList = notImpl('gateway-http/queryCompanyList')
export const queryCreditCompany = notImpl('gateway-http/queryCreditCompany')
export const queryFundAssetList = notImpl('gateway-http/queryFundAssetList')
export const queryFundBondRatio = notImpl('gateway-http/queryFundBondRatio')
export const queryFundNoticeList = notImpl('gateway-http/queryFundNoticeList')
export const queryFundRateList = notImpl('gateway-http/queryFundRateList')
export const queryFundReportRecmdDate = notImpl('gateway-http/queryFundReportRecmdDate')
export const queryFundStockholdList = notImpl('gateway-http/queryFundStockholdList')
export const queryFundTop10List = notImpl('gateway-http/queryFundTop10List')
export const queryFundcbdindex = notImpl('gateway-http/queryFundcbdindex')
export const queryInvPortfolioList = notImpl('gateway-http/queryInvPortfolioList')
export const queryLimitCreditList = notImpl('gateway-http/queryLimitCreditList')
export const queryOptionalFundType = notImpl('gateway-http/queryOptionalFundType')
export const queryOptionalList = notImpl('gateway-http/queryOptionalList')
export const queryPositionDateSection = notImpl('gateway-http/queryPositionDateSection')
export const queryPositionEarningsRatioList = notImpl('gateway-http/queryPositionEarningsRatioList')
export const queryRemaindePeriod = notImpl('gateway-http/queryRemaindePeriod')
export const queryRiskSign = notImpl('gateway-http/queryRiskSign')
export const queryShareChangeList = notImpl('gateway-http/queryShareChangeList')
export const reserarchEtsReportInfo = notImpl('gateway-http/reserarchEtsReportInfo')
export const saveBillSubscribe = notImpl('gateway-http/saveBillSubscribe')
export const search = notImpl('gateway-http/search')
export const shortbondfundavgyield = notImpl('gateway-http/shortbondfundavgyield')
export const submitAccountSign = notImpl('gateway-http/submitAccountSign')
export const submitBatchRiskSign = notImpl('gateway-http/submitBatchRiskSign')
export const transferFundCode = notImpl('gateway-http/transferFundCode')
export const updateNoticeSetting = notImpl('gateway-http/updateNoticeSetting')
